version: '3'

volumes:
  static_files:

services:
  webapp:
    build:
      context: ./ccnatrainer
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - static_files:/static_files
    command: gunicorn -w 4 ccnatrainer.wsgi -b 0.0.0.0:8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 80:80
      - 443:443